### ISSUE TITLE
ABGB

### ISSUE THREAD

**Issue by samkap** [dawndelatte/tiy_assignments#19]
- added background-attachment: fixed to all photo-background sections and reoptimize all backgrounds in photoshop for smaller file sizes. (cap the width of all of them at around 2000px, if possible)

**Comment by dawndelatte** [comment]
Background-attachment : fixed looks so much better! I also resized all the photos so their width is 2000px and saved for web at a slightly lower quality. I would like to see what you think, because it still takes a few seconds to load, and I'm also wondering if they could use a blur or color overlay to set them back a little.
